# 100 numpy alıştırması | cevaplar

Bu egzersizler Numpy kütüphanesini daha derin ve detaylıca öğrenmek isteyenler için hazırlanmıştır

Numpy hakkında belli bilgileriniz varsa ve dokümantasyonu okuduysanız devam edebilirsiniz :)

#### 1) Numpy kütüphanesini  `np` olarak çağırın?

In [2]:
import numpy as np

#### 2) Numpy sürümünü ve yapılandırmasını yazdırın?

In [2]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/bigfi/anaconda3/Library/include
    lib directory: C:/Users/bigfi/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

#### 3) Boyutu 10 olan bir boş (null) vektör oluşturun?

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4) Herhangi bir dizinin bellek boyutunu nasıl bulursunuz?

In [4]:
Zeros = np.zeros((5,5))
print("%d bytes" % (Zeros.size * Zeros.itemsize))

200 bytes


#### 5) Komut satırından numpy.add işlevinin dokümantasyonunu nasıl alırsınız?

In [30]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6) Boyutu 10 olan bir boş vektör oluşturun ancak beşinci değeri 1 olsun? 

In [31]:
Zeros = np.zeros(10)
Zeros[4] = 1
print(Zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7) 10'dan 49'a kadar olan değerlerle bir vektör oluşturun?

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8) Bir vektörü ters çevirin (ilk elemanı son eleman yapın)

In [9]:
ReverseVector = np.arange(0,21)
ReverseVector = ReverseVector[::-1]
ReverseVector

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

#### 9) 0'dan 8'e kadar aralığı olan 3x3 Boyutunda bir matris oluşturun

In [11]:
MyMatrix = np.arange(0,9)
MyMatrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10) [1,2,0,0,4,0] dizisindeki sıfır olmayan elemanların dizinlerini bulun?

In [32]:
Dizi = [1,2,0,0,4,0]
np.nonzero(Dizi)

(array([0, 1, 4], dtype=int64),)

#### 11) Bir 3x3 birim (idendity) matris oluşturun?

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12) Rastgele değerlerle bir 3x3x3 dizi oluşturun

In [14]:
np.random.random((3,3,3))

array([[[0.48516617, 0.86007571, 0.77885743],
        [0.44955215, 0.51515844, 0.53408831],
        [0.33765246, 0.65883707, 0.45659811]],

       [[0.7856543 , 0.44807061, 0.29378383],
        [0.74121455, 0.55172274, 0.42702842],
        [0.06020619, 0.25014365, 0.18664024]],

       [[0.60632882, 0.9161759 , 0.16029022],
        [0.82972847, 0.57383495, 0.6204742 ],
        [0.08342289, 0.37704152, 0.75013234]]])

#### 13) Rastgele değerlerle bir 10x10 dizi oluşturun ve minimum ve maksimum değerleri bulun

In [35]:
Z = np.random.rand(10,10)
print(Z.min())
print(Z.max())

0.016934268889001958
0.9859266641563288


#### 14) Boyutu 30 olan rastgele bir vektör oluşturun ve ortalama değeri bulun

In [16]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5132133206651612


#### 15) Kenarlarda 1, içeride 0 olan bir 2d dizi oluşturun

In [18]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16) Mevcut "1" dizisinin kenarları (0'larla dolu)  sınırlar nasıl eklenir?

In [20]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17) Aşağıdaki ifadelerin sonucu nedir?

 ```python
    0 * np.nan
    np.nan == np.nan
    np.inf > np.nan
    np.nan - np.nan
    np.nan in set([np.nan])
    0.3 == 3 * 0.1 0.1\n* 0.1

In [23]:
False

False

#### 18) Diyagonalın hemen altındaki 1,2,3,4 değerleriyle bir 5x5 matris oluşturun?

In [24]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19) 8x8 bir matris oluşturun ve dama tahtası deseni elde edin

In [25]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20) (6,7,8) şekilli bir dizi oluşturun, 100. elemanın indeksi (x,y,z) nedir?

In [26]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21) Tile fonksiyonunu kullanarak 8x8 dama tahtası matrisi oluşturun?

In [27]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22) 5x5 rastgele bir matrisi normalleştirin

In [28]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
Z

array([[ 1.36998988, -0.58717271, -1.22701314, -0.98067465, -0.44604045],
       [ 1.21898151, -1.07341999,  0.78811022, -0.36446601,  0.16937135],
       [ 1.05289996, -1.26276004, -1.00859496, -0.62007423,  0.13306854],
       [-0.61292803,  0.94660833, -1.0694927 , -0.47124153, -1.26737351],
       [ 1.29378275,  1.48168645,  1.48443913, -0.39534513,  1.44765897]])

#### 23. Renkleri dört işaretsiz bayt (RGBA) olarak tanımlayan özel bir dtype oluşturun

In [38]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24) 5x3 bir matrisi 3x2 bir matris ile çarpın (gerçek matris çarpımıyla)

In [34]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))

# veya Python 3.5 üstü iin alternatif çözüm

Z = np.ones((5,3)) @ np.ones((3,2))
Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25) 1D bir dizi verildiğinde, 3 ile 8 arasındaki tüm elemanları olumsuzlayın.

In [35]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26) Aşağıdaki betiğin çıktısı nedir?

 ```python
print(sum(range(5),-1))
    
from numpy import 
    
print(sum(range(5),-1))


In [38]:
9
10

10

#### 27) 5x5 boyutunda bir rastgele matris oluşturun

In [5]:
MyMatrix = np.random.randint(0,25,25)
MyMatrix.reshape(5,5)

array([[12, 24,  1, 15, 13],
       [ 4,  8, 18, 18,  1],
       [ 6,  8,  6, 18, 24],
       [14,  9,  6, 18,  0],
       [23, 22, 20, 12,  1]])

#### 28) Aşağıdaki ifadelerin sonucu nedir?
```python
np.seterr(all='ignore')

print(np.array(0) / np.array(0))  # nan
print(np.array(0) // np.array(0))  # 0
print(np.array([np.nan]).astype(int).astype(float))
```

In [ ]:
nan
0
[-2.14748365e+09]

#### 29) Bir float dizisini sıfırdan uzağa nasıl yuvarlarsınız?

In [59]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-10.  -5.   6.  -7.   7.  -8.  -7.  -6.  -8.   1.]


#### 30) İki dizi arasındaki ortak değerleri nasıl bulursunuz?

In [69]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[5 0 0 2 0 8 6 2 7 5]
[8 2 6 7 8 3 2 6 8 1]
[2 6 7 8]


#### 31) Tüm numpy uyarılarını nasıl yok sayarsınız (önerilmez)?

In [70]:
# Suicide modu açık!
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Sanity' ye dönüş
_ = np.seterr(**defaults)

# Equivalently -  içerik yöneticisiyle birlikte
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32) Aşağıdaki ifadeler doğru mudur?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```


In [ ]:
Yanlıştır. (False)

#### 33) Dün, bugün ve yarının tarihlerini nasıl alırsınız?

In [75]:
dun = np.datetime64('today') - np.timedelta64(1)
bugun     = np.datetime64('today')
yarin  = np.datetime64('today') + np.timedelta64(1)
print(bugun)

2024-07-11


#### 34) Temmuz 2016'ya karşılık gelen tüm tarihleri nasıl alırsınız?

In [76]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35) ((A+B)*(-A/2))'yi nasıl kopyalamadan hesaplarsınız?

In [77]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36) Pozitif sayılardan oluşan rastgele bir dizinin tam sayı kısmını 4 farklı yöntemle nasıl çıkarırsınız?

In [78]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[7. 6. 7. 8. 4. 3. 5. 4. 7. 2.]
[7. 6. 7. 8. 4. 3. 5. 4. 7. 2.]
[7. 6. 7. 8. 4. 3. 5. 4. 7. 2.]
[7 6 7 8 4 3 5 4 7 2]
[7. 6. 7. 8. 4. 3. 5. 4. 7. 2.]


#### 37) Satır değerleri 0'dan 4'e kadar olan bir 5x5 matris nasıl oluşturursunuz?

In [82]:
Z = np.tile(np.arange(0, 5), (5,1))
Z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38) 10 tamsayı üreten bir fonksiyon yapın ve bunu kullanarak bir dizi oluşturun?

In [85]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39) Boyutu 10 olan ve 0 ile 1 arasında değerler içeren bir vektör oluşturun

In [87]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40) Boyutu 10 olan rastgele bir sıralı vektör oluşturun

In [89]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.13749507 0.16626432 0.42745077 0.44952634 0.5408469  0.60776262
 0.61505219 0.640401   0.67478053 0.79190055]


#### 41) Küçük bir diziyi np.sum'dan daha hızlı nasıl toplarsınız? 

In [90]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42) Rastgele iki dizi olan A ve B'yi düşünün, eşit olup olmadıklarını kontrol edin

In [94]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
equal

False

#### 43) Herhangi bir diziyi değiştirilemez (salt okunur) yapın

In [95]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44) Kartezyen koordinatları temsil eden rastgele bir 10x2 matrisini, kutupsal koordinatlara dönüştürün

In [96]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.34507774 1.28201437 0.33888516 0.52592113 0.37895101 0.80084424
 0.58357514 0.92143188 0.81806644 0.51203965]
[0.24495805 0.75204194 1.06777577 1.27077259 0.39976788 1.15603486
 1.30619071 0.0074211  1.53364986 0.10202429]


#### 45) Boyutu 10 olan rastgele bir vektör oluşturun ve maksimum değerini 0 yapın

In [97]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.68024478 0.72788099 0.81576364 0.         0.36069907 0.05033544
 0.41808269 0.39164582 0.774808   0.00486121]


#### 46) [0,1]x[0,1] alanını kaplayan x ve y koordinatlarına sahip bir yapılandırılmış dizi oluşturun

In [98]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47) İki dizi verildiğinde, X ve Y, Cauchy matrisini oluşturun 

(Cij =1/(xi - yj))

In [99]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48) Her numpy skaler türü için temsil edilebilir minimum ve maksimum değeri yazdırın

In [100]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49) Bir dizinin tüm değerlerini nasıl yazdırırsınız?

In [105]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

#### 50) Bir vektörde (belirli bir skaler) en yakın değeri nasıl bulursunuz?

In [106]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

12


#### 51) Bir pozisyonu (x,y) ve bir rengi (r,g,b) temsil eden yapılandırılmış bir dizi oluşturun

In [16]:
dtype = np.dtype([('position', [('x', float), ('y', float)]), 
                  ('color', [('r', int), ('g', int), ('b', int)])])

# Yapılandırılmış dizi oluşturma
data = np.array([((0.0, 1.0), (255, 0, 0)),
                 ((2.0, 3.0), (0, 255, 0)),
                 ((4.0, 5.0), (0, 0, 255))], dtype=dtype)

print(data)
print("Pozisyonlar:", data['position'])
print("Renkler:", data['color'])

[((0., 1.), (255,   0,   0)) ((2., 3.), (  0, 255,   0))
 ((4., 5.), (  0,   0, 255))]
Pozisyonlar: [(0., 1.) (2., 3.) (4., 5.)]
Renkler: [(255,   0,   0) (  0, 255,   0) (  0,   0, 255)]


#### 52) Koordinatları temsil eden (100,2) şekline sahip rastgele bir vektör düşünün, nokta noktaya mesafeleri bulun

In [109]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)


#  scipy ile bu işlem daha hızlı olur
import scipy
# Gavin Heverly-Coulson'e teşekkürler! 
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.80925678 0.56621591 0.55253001 0.11005035 0.26805241
  0.24661574 0.56035384 0.65674181 0.1477217 ]
 [0.80925678 0.         0.72050332 0.27203106 0.75441769 0.98146005
  1.05470998 0.24897675 0.45628199 0.73376072]
 [0.56621591 0.72050332 0.         0.4942533  0.45641451 0.50416638
  0.7392247  0.56882113 0.2871754  0.41940603]
 [0.55253001 0.27203106 0.4942533  0.         0.4873911  0.70981172
  0.79909789 0.08023454 0.29604799 0.46439009]
 [0.11005035 0.75441769 0.45641451 0.4873911  0.         0.24557691
  0.32801042 0.50919111 0.55654691 0.03793802]
 [0.26805241 0.98146005 0.50416638 0.70981172 0.24557691 0.
  0.27075592 0.74288571 0.70380585 0.25395978]
 [0.24661574 1.05470998 0.7392247  0.79909789 0.32801042 0.27075592
  0.         0.80573839 0.88219399 0.36209343]
 [0.56035384 0.24897675 0.56882113 0.08023454 0.50919111 0.74288571
  0.80573839 0.         0.37563609 0.49118753]
 [0.65674181 0.45628199 0.2871754  0.29604799 0.55654691 0.70380585
  0.88219399 0.37563

#### 53) 32 bitlik bir float dizisini yerinde 32 bitlik bir tamsayıya nasıl dönüştürürsünüz?

In [113]:
# Teşekkürler Vikas! (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[67 83 31 29 65 55  9 96  7 75]


#### 54) Aşağıdaki dosyayı nasıl okursunuz?

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [18]:
from io import StringIO

# Örnek dosya içeriği
data = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

# StringIO kullanarak dosya benzeri bir nesne oluşturma
file_like_object = StringIO(data)

# Dosyayı okuma
array = np.genfromtxt(file_like_object, delimiter=',', dtype=float)

print(array)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55) Numpy dizileri için enumerate'in karşılığı nedir?

In [114]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56) Genel bir 2D Gauss benzeri dizi oluşturun

In [115]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57) Bir 2D diziye rastgele b elemanını nasıl yerleştirirsiniz?

In [28]:
array = np.zeros((6, 6), dtype=int)
n = array.size
b = 56

indices = np.random.choice(n, 3, replace=False)

np.put(array, indices, b)

print(array)

[[ 0  0 56  0 56  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [56  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


#### 58) Bir matrisin her bir satırının ortalamasını nasıl çıkarırsınız?

In [121]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.18557788  0.40521387 -0.35338599  0.32018128  0.23793131 -0.04176217
   0.35205037 -0.45517056 -0.41288837 -0.23774762]
 [-0.29914511  0.09235389  0.25299118  0.17159231  0.08814452  0.15577847
  -0.24358521 -0.08010014  0.41321075 -0.55124067]
 [-0.47101888 -0.48408073  0.35995204  0.25401575  0.16002962 -0.10947186
   0.38101518  0.1216929   0.03678442 -0.24891845]
 [ 0.41165458 -0.03727648 -0.47444964  0.0978364   0.04010538 -0.17788042
   0.46714951 -0.00647475  0.02822639 -0.34889097]
 [-0.34856416  0.05048328 -0.08490035 -0.2808731   0.32335143 -0.02933769
   0.24336856  0.20928793 -0.18385515  0.10103923]]


#### 59) Bir diziyi n'inci sütuna göre nasıl sıralarsınız?

In [122]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 1 2]
 [9 6 2]
 [6 9 4]]
[[4 1 2]
 [9 6 2]
 [6 9 4]]


#### 60) Belirli bir 2D dizide boş sütunlar olup olmadığını nasıl anlarsınız?

In [123]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


#### 61) Bir dizideki belirli bir değere en yakın olan değeri nasıl bulursunuz?

In [124]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.468765277101151


#### 62) (1,3) ve (3,1) şekline sahip iki dizi düşünün, toplamlarını bir iteratör kullanarak nasıl hesaplarsınız?

In [125]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63) Bir ad özniteliğine sahip dizi sınıfı oluşturun

In [126]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64) Belirli bir vektörü düşünün, tekrarlanan dizinlere dikkat ederek ikinci bir vektör tarafından dizinlenen her elemana 1 ekleyin


In [127]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 2. 1. 3. 2. 4. 6. 2. 5.]


#### 65) Bir vektörün (X) elemanlarını bir dizine dayalı olarak bir diziye (F) nasıl biriktirirsiniz? 


In [128]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66) (dtype=ubyte) olan (w,h,3) şekline sahip bir görüntüyü düşünün, benzersiz renklerin sayısını hesaplayın


In [129]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67) Dört boyutlu bir diziyi düşünün, son iki eksende toplamı nasıl alırsınız? 


In [42]:
array = np.random.random((3, 4, 5, 6))
sum_result = np.sum(array, axis=(-2, -1))
print(sum_result)

[[16.63117963 13.24318141 15.1762028  16.94451449]
 [15.17382519 14.43044739 14.57405564 17.85754662]
 [17.38605141 17.83893671 16.89300041 14.31984442]]


#### 68) Bir boyutlu bir vektör D oluşturun; alt kümelerin ortalamalarını, alt kümeleri tanımlayan aynı boyutta bir vektör S kullanarak nasıl hesaplayabilirsiniz? 


In [43]:

D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# Benzersiz alt küme indekslerinin sayısı kadar bir diziyi np.bincount ile oluşturun
sum_of_subsets = np.bincount(S, weights=D)
count_of_subsets = np.bincount(S)

# Alt kümelerin ortalamalarını hesaplayın
mean_of_subsets = sum_of_subsets / count_of_subsets

print(mean_of_subsets)


[5. 6.]


#### 69) Nokta çarpımının köşegenini nasıl alırsınız? 

In [45]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Nokta çarpımının köşegenini hesaplama
diagonal_elements = np.einsum('ij,ji->i', A, B)

print("Matris A:\n", A)
print("Matris B:\n", B)
print("Diyagonal elemanlar:", diagonal_elements)

Matris A:
 [[0.03648432 0.45126125 0.14427444]
 [0.19323837 0.42659287 0.90803862]
 [0.30296667 0.16236492 0.48169674]]
Matris B:
 [[0.12409675 0.70103653 0.38985543]
 [0.56842437 0.93340757 0.09168922]
 [0.60320105 0.48235651 0.15602869]]
Diyagonal elemanlar: [0.34806197 0.97165052 0.20815883]


#### 70) [1, 2, 3, 4, 5] vektörünü düşünün, her bir değerin arasına 3 ardışık sıfır ekleyerek yeni bir vektör nasıl oluşturursunuz? 


In [46]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71) (5,5,3) boyutunda bir dizi düşünün, bunu (5,5) boyutunda bir dizi ile nasıl çarparsınız? 


In [47]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72) Bir dizinin iki satırını nasıl değiştirirsiniz? #

In [50]:
Z = np.arange(25).reshape(5,5)
Z[[0,1]] = Z[[1,0]]
print(Z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73) 10 üçgeni tanımlayan 10 üçlü kümesini düşünün (paylaşılan köşelerle), tüm üçgenleri oluşturan benzersiz çizgi segmentlerini bulun 


In [51]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 20) ( 3, 21) ( 3, 36) ( 3, 77) ( 6, 85) ( 6, 87) (18, 48) (18, 82)
 (20, 36) (21, 77) (32, 44) (32, 46) (42, 55) (42, 89) (43, 62) (43, 72)
 (43, 82) (43, 98) (44, 46) (48, 60) (48, 77) (48, 82) (51, 83) (51, 97)
 (55, 89) (60, 77) (62, 82) (72, 98) (83, 97) (85, 87)]


#### 74) Bir bincount'a karşılık gelen sıralı bir C dizisi oluşturun, np.bincount(A) == C olacak şekilde bir A dizisini nasıl üretirsiniz? 


In [3]:
C = np.array([0, 3, 1, 1])
A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 1 2 3]


#### 75) Bir dizi üzerinde kayan bir pencere kullanarak ortalamaları nasıl hesaplarınız? 


In [7]:
import numpy as np

def moving_average(arr, window_size):
    cumsum = np.cumsum(np.insert(arr, 0, 0)) 
    return (cumsum[window_size:] - cumsum[:-window_size]) / float(window_size)

Z = np.arange(20)
print(moving_average(Z, 3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76) Bir boyutlu bir dizi Z'yi düşünün, ilk satırı (Z[0],Z[1],Z[2]) olan ve her bir sonraki satırın 1 kaydırıldığı iki boyutlu bir dizi oluşturun 


In [11]:
import numpy as np

Z = np.arange(1, 15)
window_size = 3
result = np.lib.stride_tricks.sliding_window_view(Z, window_size)
print(result)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]


#### 77) Bir boolean'ı nasıl olumsuzlarsınız veya bir float'ın işaretini nasıl yerinde değiştirirsiniz? 


In [12]:
# Boolean'ı olumsuzlama
bool_array = np.array([True, False, True])
np.logical_not(bool_array, out=bool_array)
print(bool_array)

# Float'ın işaretini yerinde değiştirme
float_array = np.array([1.0, -2.0, 3.0])
np.negative(float_array, out=float_array)
print(float_array)

[False  True False]
[-1.  2. -3.]


#### 78) İki nokta kümesini P0 ve P1 şeklinde oluşturun, her bir noktadan i (P0[i],P1[i]) geçen çizgiye bir p noktası p'yi nasıl hesaplarsınız? 


In [13]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.83172337 11.53379492  2.57523195  6.26536813  4.52629017  8.05677995
  2.01859185  3.72844017  0.08635115  1.86212003]


#### 79) İki nokta kümesini P0 ve P1 ve bir P noktaları kümesini düşünün, her bir P[j] noktası ile her bir (P0[i], P1[i]) çizgisi arasındaki mesafeyi nasıl hesaplarsınız?


In [ ]:
# bir önceki sorudan base alınmıştır
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80) Keyfi bir diziyi düşünün, sabit bir şekle sahip bir alt kısmı çıkaran ve belirli bir eleman üzerine merkezlenen bir fonksiyon yazın (gerektiğinde bir dolgu değeri ile doldurun) 


In [15]:
def extract_subarray(arr, center, shape, fill_value=0):
    arr = np.asarray(arr)
    center = np.array(center)
    shape = np.array(shape)
    
    half_shape = (shape - 1) // 2
    start = center - half_shape
    end = start + shape
    
    slices = [slice(max(0, s), min(e, d)) for s, e, d in zip(start, end, arr.shape)]
    result = np.full(shape, fill_value, dtype=arr.dtype)
    
    insert_slices = [slice(max(0, -s), min(e - s, d)) for s, e, d in zip(start, end, shape)]
    result[tuple(insert_slices)] = arr[tuple(slices)]
    
    return result

arr = np.arange(25).reshape(5, 5)
center = (2, 2)
shape = (3, 3)
result = extract_subarray(arr, center, shape, fill_value=-1)
print(result)

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


#### 81) Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] dizisini düşünün, R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...] olacak şekilde kaydırılmış bir 4x4 dizi oluşturun? 


In [16]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, window_shape=(4,))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82) Düz bir dizi üzerinde 3x3 maksimum filtre nasıl uygulanır? 


In [18]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83) 5 boyutlu bir dizinin en büyük 10 değerini nasıl bulursunuz? 


In [22]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84) Bir vektördeki yinelenen öğelerin dizinlerini bulun 

In [23]:
v = np.array([1, 2, 3, 2, 4, 3, 5, 1])

unique_elements, indices = np.unique(v, return_inverse=True)
repeated_indices = np.split(np.argsort(indices), np.cumsum(np.bincount(indices))[:-1])
print(repeated_indices)







[array([0, 7], dtype=int64), array([1, 3], dtype=int64), array([2, 5], dtype=int64), array([4], dtype=int64), array([6], dtype=int64)]


#### 85) Büyük bir 2D dizi ve 2D blokların her birini maksimuma göre sıralayarak diziyi parçalara ayıran bir fonksiyon yazın 


In [24]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 15  1  6  7]
 [15  2  6  0  7]
 [ 1  6  8 42 12]
 [ 6  0 42  3  2]
 [ 7  7 12  2  9]]


#### 86) 3D koordinatların konveks kovanını bulun 

In [26]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87) 100.000 elemanlık rastgele bir vektör ve 5000 elemanlık rastgele bir vektör oluşturun, ikincisindeki her değerin birincisinde var olup olmadığını kontrol edin 


In [28]:
large_vector = np.random.randint(0, 1000, size=100000)
small_vector = np.random.randint(0, 1000, size=5000)

result = np.isin(small_vector, large_vector)
print(result)

[ True  True  True ...  True  True  True]


#### 88) Büyük bir vektörü düşünün, belirli bir aralığın değerlerini sıralamak için en hızlı yolu bulun 


In [29]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89) Büyük bir dizi üzerinde maksimum değerlerin bir türün ortaya çıkma sayısına göre sıralandığı argmax işlevi yazın 


In [30]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9998 9999 9997 9995]


#### 90) np.array isimli yapılandırılmış bir dizi oluşturun, rengi beyaz olan her eleman için tüm beyaz öğeleri seçen bir maske oluşturun 


In [32]:
dtype = [('x', float), ('y', float), ('color', 'U10')]
data = np.array([(1, 2, 'red'), (3, 4, 'white'), (5, 6, 'white'), (7, 8, 'blue')],
                dtype=dtype)

mask = data['color'] == 'white'

print(mask)

[False  True  True False]


#### 91) Bir düzenli diziden nasıl kayıt dizisi oluşturulur? 

In [35]:
Z = np.array([("Selam", 2.5, 3),
              ("Dunya", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Selam', 2.5, 3) (b'Dunya', 3.6, 2)]


#### 92) Büyük bir vektör Z düşünüldüğünde, Z'nin 3 üssü 3 farklı yöntemle nasıl hesaplanır? 


In [37]:

Z = np.random.rand(10)

# 1. Yöntem: np.power kullanarak
result_power = np.power(Z, 3)

# 2. Yöntem: Operatör ** kullanarak
result_operator = Z ** 3

# 3. Yöntem: np.einsum kullanarak
result_einsum = np.einsum('i,i,i->i', Z, Z, Z)

# Sonuçları yazdırın
print("np.power ile hesaplanan sonuç:")
print(result_power)
print("\nOperatör ** ile hesaplanan sonuç:")
print(result_operator)
print("\nnp.einsum ile hesaplanan sonuç:")
print(result_einsum)

np.power ile hesaplanan sonuç:
[0.55160784 0.09890206 0.00393207 0.80695024 0.81306362 0.00806722
 0.06895492 0.12077087 0.34849567 0.1470254 ]

Operatör ** ile hesaplanan sonuç:
[0.55160784 0.09890206 0.00393207 0.80695024 0.81306362 0.00806722
 0.06895492 0.12077087 0.34849567 0.1470254 ]

np.einsum ile hesaplanan sonuç:
[0.55160784 0.09890206 0.00393207 0.80695024 0.81306362 0.00806722
 0.06895492 0.12077087 0.34849567 0.1470254 ]


#### 93) Şekli (8,3) ve (2,2) olan iki dizi A ve B düşünüldüğünde, B'nin her bir satırındaki öğelerin sırasız olarak A'nın hangi satırlarında bulunduğunu nasıl bulunur? 


In [38]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 6 7]


#### 94) 10x3 matris düşünüldüğünde, eşit olmayan değerlere sahip satırlar nasıl çıkarılır? (örn. [2,2,3]) 


In [39]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 0 3]
 [4 0 3]
 [1 3 0]
 [4 1 4]
 [1 3 1]
 [2 3 3]
 [2 2 4]
 [1 1 0]
 [0 2 4]
 [4 0 0]]
[[1 0 3]
 [4 0 3]
 [1 3 0]
 [4 1 4]
 [1 3 1]
 [2 3 3]
 [2 2 4]
 [1 1 0]
 [0 2 4]
 [4 0 0]]
[[1 0 3]
 [4 0 3]
 [1 3 0]
 [4 1 4]
 [1 3 1]
 [2 3 3]
 [2 2 4]
 [1 1 0]
 [0 2 4]
 [4 0 0]]


#### 95) Bir tamsayı vektörünü bir matris ikili temsiline nasıl dönüştürülür? 


In [42]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96) İki boyutlu bir diziden benzersiz satırlar nasıl çıkarılır? 


In [44]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]]


#### 97) İki vektör A & B düşünüldüğünde, inner, outer, sum ve mul fonksiyonlarının einsum eşdeğeri nasıl yazılır? 

In [46]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.32342181, 0.59955668, 0.08459548, 0.47452232, 0.69182919,
        0.44508903, 0.6691592 , 0.50638201, 0.43262414, 0.21439219],
       [0.07257105, 0.13453162, 0.01898197, 0.10647577, 0.1552362 ,
        0.09987137, 0.15014939, 0.11362461, 0.09707444, 0.04810642],
       [0.17328203, 0.3212288 , 0.04532433, 0.25423824, 0.37066631,
        0.23846855, 0.35852024, 0.27130794, 0.23179015, 0.11486645],
       [0.04280018, 0.07934262, 0.01119498, 0.06279614, 0.09155354,
        0.05890107, 0.0885535 , 0.0670123 , 0.05725152, 0.02837169],
       [0.33121944, 0.61401186, 0.08663506, 0.48596295, 0.70850905,
        0.45582003, 0.68529249, 0.51859077, 0.44305461, 0.21956114],
       [0.11213624, 0.20787724, 0.0293308 , 0.16452555, 0.2398698 ,
        0.15432049, 0.23200971, 0.17557188, 0.14999868, 0.07433368],
       [0.3519401 , 0.65242365, 0.09205484, 0.51636417, 0.75283246,
        0.48433554, 0.7281635 , 0.55103314, 0.47077154, 0.2332966 ],
       [0.05761841, 0.10681254, 0.0150709

#### 98) İki vektör (X,Y) tarafından tanımlanan bir yol düşünüldüğünde, eşit aralıklı örnekleme kullanarak nasıl örneklenir? 


In [47]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99) Bir tamsayı n ve 2D bir dizi X verildiğinde, X'ten n dereceli bir multinom dağılımı olarak yorumlanabilecek satırları nasıl seçilir? 


In [51]:
X = np.array([1, 2, 3, 4, 5])
Y = np.array([6, 7, 8, 9, 10])

num_samples = 10

# X ve Y vektörlerini eşit aralıklı örneklerle örnekleyin
X_sampled = np.interp(np.linspace(0, 1, num_samples), np.linspace(0, 1, len(X)), X)
Y_sampled = np.interp(np.linspace(0, 1, num_samples), np.linspace(0, 1, len(Y)), Y)

print("X örnekleme:", X_sampled)
print("Y örnekleme:", Y_sampled)

X örnekleme: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
Y örnekleme: [ 6.          6.44444444  6.88888889  7.33333333  7.77777778  8.22222222
  8.66666667  9.11111111  9.55555556 10.        ]


#### 100) Bir 1D dizinin ortalaması için bootstrap yöntemiyle %95 güven aralıkları nasıl hesaplanır? 

In [49]:
X = np.random.randn(100) 
N = 1000 # bootstrap örnek sayısı
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12829619  0.27194381]


#### Tebrikler! Alıştırmanın sonuna geldiniz :)