In [1]:
import numpy as np

In [15]:
np.__version__

'1.26.4'

## Normal dizi oluşturma

In [16]:
dizi_1 = [1,2,3,4,5]
type(dizi_1)
print(dizi_1)

[1, 2, 3, 4, 5]


## numpy dizi oluşturma

In [27]:
np_dizi = np.array([0,1,2,13,4,5])
type(np_dizi)

numpy.ndarray

In [29]:
np_dizi[3]

13

In [19]:
np_dizi[-2] #sondan 2.yi getir demek

4

In [ ]:
np_dizi[:2]

array([0, 1])

In [21]:
np_dizi[2:]

array([ 2, 13,  4,  5])

In [22]:
np_dizi[1:4]

array([ 1,  2, 13])

In [23]:
np_dizi[:3] = 100

In [24]:
print(np_dizi)

[100 100 100  13   4   5]


In [25]:
np_dizi_2 = np_dizi *10

In [26]:
np_dizi_2

array([1000, 1000, 1000,  130,   40,   50])