In [1]:
import numpy as np

In [5]:
matris = np.array([[1,2,3,],[4,5,6],[7,8,9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Matrisin temel özellikleri

In [10]:
print(f"boyut sayısı:{matris.ndim} ")

boyut sayısı:2 


In [26]:
print(matris[2,1])
print(matris[0,2])

8
3


In [28]:
matris[1,1]= 500

In [30]:
matris

array([[  1,   2,   3],
       [  4, 500,   6],
       [  7,   8,   9]])

# Transpoz

In [35]:
matris

array([[  1,   2,   3],
       [  4, 500,   6],
       [  7,   8,   9]])

In [39]:
matris_tr = matris.T

In [41]:
matris_tr

array([[  1,   4,   7],
       [  2, 500,   8],
       [  3,   6,   9]])