In [13]:
import numpy as np

# np.arange

In [3]:
# np.array(başla,bitir,adımla, dtype)

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(5,20,5)

array([ 5, 10, 15])

# örnekler

In [22]:
# 25 dan 60 a kadar sayıları 3 er 3 er yazdır

In [34]:
ornek_1 = np.arange(25,60,3)
print(ornek_1)

[25 28 31 34 37 40 43 46 49 52 55 58]


# np.linspace

In [38]:
# np.linspace(başla,bitir,sayı_adedi)

In [58]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [56]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [60]:
np.linspace(0,10,30, dtype= int)

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9, 10])

In [ ]:
# 30 dan 95 e kadar aralığı olan 70 tane sayı yazdır

In [65]:
np.linspace(30,95, 70, dtype= int)

array([30, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
       94, 95])

In [71]:
ornek_2 = np.linspace(30,95,70)
print(ornek_2)

[30.         30.94202899 31.88405797 32.82608696 33.76811594 34.71014493
 35.65217391 36.5942029  37.53623188 38.47826087 39.42028986 40.36231884
 41.30434783 42.24637681 43.1884058  44.13043478 45.07246377 46.01449275
 46.95652174 47.89855072 48.84057971 49.7826087  50.72463768 51.66666667
 52.60869565 53.55072464 54.49275362 55.43478261 56.37681159 57.31884058
 58.26086957 59.20289855 60.14492754 61.08695652 62.02898551 62.97101449
 63.91304348 64.85507246 65.79710145 66.73913043 67.68115942 68.62318841
 69.56521739 70.50724638 71.44927536 72.39130435 73.33333333 74.27536232
 75.2173913  76.15942029 77.10144928 78.04347826 78.98550725 79.92753623
 80.86956522 81.8115942  82.75362319 83.69565217 84.63768116 85.57971014
 86.52173913 87.46376812 88.4057971  89.34782609 90.28985507 91.23188406
 92.17391304 93.11594203 94.05797101 95.        ]
