In [1]:
import numpy as np

# np.random.rand

In [13]:
np.random.randn(5,5).size

25

In [15]:
np.random.randn(5,5)

array([[-0.09248921, -0.7458729 , -0.81826292,  0.37364276,  1.05670122],
       [-0.35998133,  0.88691862, -0.86390166, -1.25181384,  2.02012119],
       [-0.92980906,  1.22892929, -0.41605532,  0.65022196,  2.24247746],
       [-1.65074039, -1.53433532, -0.33011511, -2.4193694 , -1.55302062],
       [ 0.88854073, -0.84033806, -1.36353458,  1.77760961, -0.30015869]])

In [17]:
np.random.randn(5)

array([ 0.14408405, -0.51654779, -0.9448262 ,  1.22838452, -1.59957383])

# np.random.randint

In [24]:
# np.random.randint(başla,bitir,aralık)

In [26]:
 np.random.randint(10)

4

In [34]:
np.random.randint(10,20,25)

array([19, 12, 10, 14, 11, 17, 13, 16, 19, 16, 11, 18, 16, 11, 14, 19, 16,
       14, 19, 15, 13, 16, 15, 19, 15])

# np.random.choice

In [39]:
random_dizi = np.random.randint(1,100,10)

In [41]:
random_dizi

array([59, 15,  7, 64, 66, 19, 86, 64, 37, 93])

In [43]:
np.random.choice(random_dizi, size=10)

array([19, 59, 19, 64, 86, 37, 15, 19, 19, 15])