In [2]:
import numpy as np

## veri oluşturma

In [4]:
dizi = np.arange(10)
dizi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
matris = np.eye(5,dtype= int) # birim matris oluşturma.
matris

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
matris[4,:] # son satırın oldugu kısmı getirdi..

array([0, 0, 0, 0, 1])

In [18]:
boyut = 4  # 4x4 birim matris
birim_matris = np.eye(boyut)

print(birim_matris)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## slice işlemi

In [28]:
sl_matris = matris[1,:]

In [30]:
sl_matris

array([99, 99, 99, 99, 99])

In [26]:
sl_matris[:] = 99 # sl_matrisin içindeki tüm sayılar 99 olsun demek.

In [24]:
sl_matris

array([0, 1, 0, 0, 0])

In [26]:
matris[1,:] = 99

In [30]:
matris

array([[ 1,  0,  0,  0,  0],
       [99, 99, 99, 99, 99],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  1]])