In [6]:
import numpy as np

## veri oluşturma

In [7]:
dizi_a = np.arange(1,11)
print(dizi_a)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
dizi_b = np.random.randint(1,20,10)
print(dizi_b)

[17 12  3  3 18  5 13 16 17  8]


## işlemler

In [9]:
dizi_c = dizi_a + dizi_b # ayrıca - , * , / , % işlemleri de yapabiliyoruz
print(dizi_c)

[18 14  6  7 23 11 20 24 26 18]


## istatistiksel gösterimler

In [10]:
ist_dizi = np.random.randint(1,100,25)
print(ist_dizi)

[90 38 18 64 83 76 93 13 45 61 28 47 92 75 32 78 44 15 18 32 86 65 42 72
 35]


In [11]:
np.sum(ist_dizi) # dizinin içindeki tüm sayılar toplamı

np.int64(1342)

In [12]:
np.mean(ist_dizi) #ortalaması

np.float64(53.68)

In [13]:
np.var(ist_dizi) #varyans

np.float64(665.8975999999999)

In [14]:
np.std(ist_dizi) #standart sapma

np.float64(25.804991765160473)

## kıyaslamalar

In [15]:
dizi_d = np.random.randint(1,500,20)

In [16]:
matris_d = dizi_d.reshape(5,4)

In [17]:
matris_d

array([[465, 234, 277, 252],
       [496, 430, 176, 240],
       [  6, 159, 398, 464],
       [310,   3, 177,  97],
       [442, 202, 151, 368]], dtype=int32)

In [18]:
sonuc_d = matris_d < 200

In [20]:
matris_d[sonuc_d]

array([176,   6, 159,   3, 177,  97, 151], dtype=int32)