In [2]:
import numpy as np

## veri oluşturma

In [29]:
dizi_a = np.arange(1,11)
print(dizi_a)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
dizi_b = np.random.randint(1,20,10)
print(dizi_b)

[ 7  5 12  7  7 15 18  8 17 16]


## işlemler

In [40]:
dizi_c = dizi_a + dizi_b # ayrıca - , * , / , % işlemleri de yapabiliyoruz
print(dizi_c)

[ 8  7 15 11 12 21 25 16 26 26]


## istatistiksel gösterimler

In [8]:
ist_dizi = np.random.randint(1,100,25)
print(ist_dizi)

[90 55 56 66  1 29 57 79 61 85 95 74 54 53 32 59  2 95 75 70 70 29 29 91
 56]


In [10]:
np.sum(ist_dizi) # dizinin içindeki tüm sayılar toplamı

1463

In [12]:
np.mean(ist_dizi) #ortalaması

58.52

In [14]:
np.var(ist_dizi) #varyans

662.5696

In [16]:
np.std(ist_dizi) #standart sapma

25.74042734687985

## kıyaslamalar

In [18]:
dizi_d = np.random.randint(1,500,20)

In [20]:
matris_d = dizi_d.reshape(5,4)

In [22]:
matris_d

array([[ 23, 153, 279, 100],
       [147, 199, 413, 212],
       [476, 222, 381, 475],
       [382, 241, 319,   5],
       [204, 217, 455, 426]])

In [26]:
sonuc_d = matris_d < 200

In [28]:
matris_d[sonuc_d]

array([ 23, 153, 100, 147, 199,   5])